#!/bin/bash


YEET=${PWD}

BASEDIR=$(dirname $0)

BASEDIR="${BASEDIR:2}"

cd linux
cd ..


#If the project is already cloned you can comment out the following line
git clone --depth=1 -b rpi-4.14.y https://github.com/raspberrypi/linux.git


cd linux

chmod +777 ../ -R

KERNEL=kernel8
make -j4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcmrpi3_defconfig
make -j4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- all

rm -f ./drivers/char/Makefile
rm -f ./drivers/char/Kconfig

cp ${YEET}/${BASEDIR}/Kconfig ./drivers/char/Kconfig
cp ${YEET}/${BASEDIR}/Makefile ./drivers/char/Makefile
cp ${YEET}/${BASEDIR}/morsegpio.c ./drivers/char/morsegpio.c
cp ${YEET}/${BASEDIR}/morsegpio.h ./drivers/char/morsegpio.h

KERNEL=kernel8
make -j4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- all

chmod +777 ../ -R

cp ./arch/arm64/boot/Image ../kernel8.img
